# Generated by Django 3.1.3 on 2021-03-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20201224_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
    ]
