# Generated by Django 3.1.3 on 2021-03-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20210316_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
    ]
