# Generated by Django 3.1.3 on 2021-03-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210321_0746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='status',
        ),
    ]
